import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { api } from "../lib/api";

export default function Insights() {
  const [datasets, setDatasets] = useState([]);
  const [selected, setSelected] = useState(null);
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    api.listDatasets().then((d) => {
      setDatasets(d);
      if (d[0]) setSelected(d[0].id);
    });
  }, []);

  const generate = async () => {
    if (!selected) return;
    setBusy(true); setText("");
    try { const r = await api.insights(selected); setText(r.insights); }
    catch (e) { setText(`Error: ${e.message}`); }
    finally { setBusy(false); }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Sparkles className="text-accent-400" /> AI Insights
        </h1>
        <p className="text-sm text-slate-400 mt-1">Executive summary generated by Claude Sonnet 4.</p>
      </div>

      <div className="card p-5 flex items-center gap-3">
        <select className="input max-w-xs" value={selected || ""} onChange={(e) => setSelected(Number(e.target.value))}>
          {datasets.length === 0 && <option>No datasets</option>}
          {datasets.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
        </select>
        <button onClick={generate} disabled={!selected || busy} className="btn-primary">
          {busy ? "Analyzing…" : "Generate insights"}
        </button>
      </div>

      {text && (
        <div className="card p-6 whitespace-pre-wrap leading-relaxed text-slate-200">{text}</div>
      )}
    </div>
  );
}
